"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.runProxyRouteTests = void 0;
const strict_1 = __importDefault(require("node:assert/strict"));
const public_routes_1 = require("../lib/shared/auth/public-routes");
const roles_1 = require("../lib/shared/auth/roles");
const proxy_1 = require("../lib/backend/auth/proxy");
function runProxyRouteTests() {
    const completedTests = [];
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/forgot-password"), true);
    completedTests.push("forgot-password route is public");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/reset-password"), true);
    completedTests.push("reset-password route is public");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/access"), true);
    completedTests.push("access hub route is public");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/access/procurement-officer"), true);
    completedTests.push("procurement-officer placeholder route is public");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/access/department-user"), true);
    completedTests.push("department-user continuation route is public");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/dev/email-inbox"), true);
    completedTests.push("development email inbox route is public");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/platform-admin/login"), true);
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/platform-admin/setup-2fa"), true);
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/platform-admin/verify"), true);
    completedTests.push("platform-admin login and 2FA routes remain public even though the rest of the platform-admin namespace is protected");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/dashboard"), false);
    completedTests.push("dashboard route is not public");
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/platform-admin"), false);
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/tenant-admin"), false);
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/po"), false);
    strict_1.default.equal((0, public_routes_1.isKnownPublicRoute)("/du"), false);
    completedTests.push("role dashboards remain protected and are never classified as public routes");
    strict_1.default.deepEqual(public_routes_1.PUBLIC_ROUTES.filter((route) => route.includes("password")), ["/forgot-password", "/reset-password"]);
    completedTests.push("public route registry includes the reset flow entry points");
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.includes("/access"), true);
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.includes("/access/procurement-officer"), true);
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.includes("/access/department-user"), true);
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.includes("/dev/email-inbox"), true);
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.includes("/platform-admin/login"), true);
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.includes("/platform-admin/setup-2fa"), true);
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.includes("/platform-admin/verify"), true);
    completedTests.push("public route registry includes the role-aware access hub plus the reserved PO and DU role-entry surfaces without broadening protected role prefixes");
    strict_1.default.equal(public_routes_1.PUBLIC_ROUTES.every((route) => (0, roles_1.getProtectedRouteRole)(route) === null), true);
    completedTests.push("proxy public routes stay separate from the centralized role-based route map");
    strict_1.default.equal(proxy_1.SESSION_EXPIRED_REDIRECT_PATH, "/login?reason=session_expired");
    completedTests.push("protected route redirects preserve the session_expired login reason");
    strict_1.default.equal(proxy_1.PROTECTED_ROUTE_CACHE_HEADERS["Cache-Control"], "private, no-store, no-cache, max-age=0, must-revalidate");
    strict_1.default.equal(proxy_1.PROTECTED_ROUTE_CACHE_HEADERS.Pragma, "no-cache");
    strict_1.default.equal(proxy_1.PROTECTED_ROUTE_CACHE_HEADERS.Expires, "0");
    completedTests.push("protected route cache headers disable replay of authenticated content");
    strict_1.default.equal(proxy_1.PROTECTED_ROUTE_SECURITY_HEADERS["X-Frame-Options"], "DENY");
    strict_1.default.equal(proxy_1.PROTECTED_ROUTE_SECURITY_HEADERS["X-Content-Type-Options"], "nosniff");
    strict_1.default.equal(proxy_1.PROTECTED_ROUTE_SECURITY_HEADERS["Referrer-Policy"], "same-origin");
    completedTests.push("protected route security headers apply baseline clickjacking, sniffing, and referrer hardening");
    return completedTests;
}
exports.runProxyRouteTests = runProxyRouteTests;
